name: Eli Howey
timezone: "America/New York"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - README.md
  - tsconfig.json

plugins:
  - jekyll-sitemap